name: Docker Image CI

on:
  push:
    branches: ["main"]
    tags: ["v[0-9].[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: washed
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: |
            linux/amd64
            linux/arm64

      - run: echo "FULL_IMAGE_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - run: echo "IS_SAMVER_TAG=$(echo ${{ env.FULL_IMAGE_TAG }} | grep '^v[0-9]*\.[0-9]*\.[0-9]*$' -c)" >> $GITHUB_ENV

      - name: Create semver image tags
        if: ${{ env.IS_SAMVER_TAG == 1 }}
        run: |
          echo "MAJOR_IMAGE_TAG=$(echo ${{ env.FULL_IMAGE_TAG }} | cut -d . -f 1)" >> $GITHUB_ENV
          echo "MINOR_IMAGE_TAG=$(echo ${{ env.FULL_IMAGE_TAG }} | cut -d . -f 1,2)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: |
            ghcr.io/washed/edgedb-ingest:latest
            ghcr.io/washed/edgedb-ingest:${{ env.FULL_IMAGE_TAG }}
          platforms: |
            linux/amd64
            linux/arm64

      - name: Build and push additional semver images
        uses: docker/build-push-action@v3
        if: ${{ env.IS_SAMVER_TAG == 1 }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: |
            ghcr.io/washed/edgedb-ingest:${{ env.MAJOR_IMAGE_TAG }}
            ghcr.io/washed/edgedb-ingest:${{ env.MINOR_IMAGE_TAG }}
          platforms: |
            linux/amd64
            linux/arm64
